### ISSUE TITLE
Can't grab modifier.

### ISSUE THREAD

**Issue by rochr4** [jaywilkas/xpytile#7]
xpytile-git r70.279a499-1 here, getModifierCode.py can't grab any key:

X protocol error: <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1717, sequence_number = 17, major_opcode = 33, minor_opcode = 0

xpytile spams with similiar repeating strings like:

X protocol error: <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1717, sequence_number = 29, major_opcode = 33, minor_opcode = 0

Right now I use it like this: kill $(pgrep -f "python /usr/bin/xpytile") || $(nohup xpytile > /dev/null 2>&1) &
configured to one workspace doing its auto tilling magic which is great as it is.

Can I send a signal to it somehow (like in bspwm) beacause I am willing to make a functional menu with rofi and myrmidon: https://github.com/moustacheful/myrmidon

tryied shinglify but it is beyond of simply tiling: https://gitlab.com/corthbandt/shinglify-bin/-/tree/latest

Thanks!

**Comment by himanshugoswamiii** [comment]
> xpytile spams with similiar repeating strings like:
> 
> X protocol error: <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1717, sequence_number = 29, major_opcode = 33, minor_opcode = 0

This error is probably occuring because the keybinding that **xpytile** is trying to access is already in use by your window manager

Change all your window manager keybindings to their default

**Comment by himanshugoswamiii** [comment]
@rochr4 If you're trying to get the modifer code of a key use this 

You may have to install `xev`

```
xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
```
Now Press any key and you'll get it's modifier

**Comment by jaywilkas** [comment]
Your problem looks like conflicting keybindings.You wrote, you "configured it to one workspace". This is not possible, since xpytile handles all workspaces, even ones that are dynamically added at runtime.Regarding sending a signal to the script: You could use something like xdotool to send simulated keypresses to the script. Apart from that, there is nothing implemented in xpytile in order to retrieve signals. But adding the ability to remote control xpytile sounds interesting. What actions would you like to control or what actions in general do you suggest should be controlable?--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.

 
  
  
 
 Am 10.11.22, 17:03 schrieb rochr4 ***@***.***>:

   
  xpytile-git r70.279a499-1 here, getModifierCode.py can't grab any key: 
  X protocol error: <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1717, sequence_number = 17, major_opcode = 33, minor_opcode = 0 
  xpytile spams with similiar repeating strings like: 
  X protocol error: <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1717, sequence_number = 29, major_opcode = 33, minor_opcode = 0 
  Right now I use it like this: kill $(pgrep -f "python /usr/bin/xpytile") || $(nohup xpytile > /dev/null 2>&1) & configured to one workspace doing its auto tilling magic which is great as it is. 
  Can I send a signal to it somehow (like in bspwm) beacause I am willing to make a functional menu with rofi and myrmidon: https://github.com/moustacheful/myrmidon 
  tryied shinglify but it is beyond of simply tiling: https://gitlab.com/corthbandt/shinglify-bin/-/tree/latest 
  Thanks!

**Comment by rochr4** [comment]
> You wrote, you "configured it to one workspace". This is not possible, since xpytile handles all workspaces, even ones that are dynamically added at runtime.
>
I did it like this:
```
[DefaultTilerPerDesktop]
Desktop1 = 0
Desktop2 = 1
[maximizeWhenOneWindowLeft]
Desktop1 = False
Desktop2 = True
```
> Regarding sending a signal to the script:
>
It could be made like this: [What does kill -USR1 %1 do?](https://superuser.com/questions/1607829/what-does-kill-usr1-1-do)
> What actions would you like to control or what actions in general do you suggest should be controlable?
>
In my use case it would be:
`Super_L - ESC     swap current window with top/left-most window`
I am short on free Mod+ keys and there are only so many. Super_L works with xpytile but again free keys are super short here.
> xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
>
Thank You but it's not that I cannot identify a keycode etc. It's not this project fault but my use case.
I will experiment with xdotool (already using it like: xdotool sleep 0.250 key --clearmodifiers F11)
If it fails it might be a good reason to jump to keyboard daemon like: [Hawck](https://github.com/snyball/Hawck) or [Sxhkd](https://wiki.archlinux.org/title/Sxhkd)
I do really hope I can succesfully integrate xpytile into my workflow, worst scenario is to switch from xfwm4 to awesomewm.
Thanks again for Your reply and advice @jaywilkas @himanshugoswamiii

P.S.
Here is a nice XFCE theme [border-only](https://www.xfce-look.org/p/1016214/) that goes well when tilling, one can identify active window easily with it as opposed to no decorations.

**Comment by rochr4** [comment]
>Apart from that, there is nothing implemented in xpytile in order to retrieve signals
>
```
echo 'Hello World!' > /proc/$(pgrep -f "python /usr/bin/xpytile")/fd/0
```
I am not a coder, feels like getting somewhere.

**Comment by jaywilkas** [comment]
@roch4  This makes no sense, since the tiler-script is (was) not able to handle incoming signals.

I added that feature now. 

Another thing: You don't need to check whether the script is already running, since the script makes sure that only one instance is running.
